server {
    listen 80;
    server_name localhost;

    # Redirection automatique du HTTP (port 80) vers le HTTPS (port 443)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # Chemins des certificats À L'INTÉRIEUR du conteneur Nginx
    ssl_certificate      /etc/nginx/certs/cert.pem;
    ssl_certificate_key  /etc/nginx/certs/key.pem;

    # Sécurité SSL de base
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          HIGH:!aNULL:!MD5;

    # Gestion du Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Gestion de l'API Backend
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Ajout des headers de sécurité pour le HTTPS
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        proxy_cookie_path / "/; SameSite=Lax; Secure"; # Ajout de "Secure" car on est en HTTPS
        
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
    }
}