FROM python:3.11-slim

WORKDIR /app

# requirements.txt est à la racine
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'app
COPY app/ .

# Copier le dossier tools depuis la racine
COPY tools/ ./tools/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]