FROM nginx:alpine

# Supprimer la page par défaut de nginx
RUN rm -rf /usr/share/nginx/html/*

# Copier les fichiers du frontend
COPY app/templates/index.html /usr/share/nginx/html/
COPY app/static/ /usr/share/nginx/html/static/

# Configuration nginx pour rediriger les appels API vers le backend
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80